language: node_js

sudo: false
branches:
  only:
    - develop
    - master

notifications:
  email: false

cache:
  directories:
    - node_modules

node_js:
  - '5'
  - '4'
  - '0.12'
  - '0.11'
  - 'iojs'

before_script:
  - npm install -g bower gulp
  - bower install
  - git config --global user.name "Travis CI"
  - git config --global user.email "ci@stomt.com"

script:
  - npm test

# already done on circleCI
#deploy:
#  - provider: script
#    script: gulp git-deploy --production
#    skip_cleanup: true
#    on:
#      branch: master
